use Univer

select AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
from AUDITORIUM a
where AUDITORIUM_CAPACITY = (select top(1) AUDITORIUM_CAPACITY from AUDITORIUM aa
where aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
order by AUDITORIUM_CAPACITY desc)

select * from AUDITORIUM